# Site settings
title: Lykourgos Tsirikos Resume
author:
  name: Lykourgos Tsirikos
  email: lykourgos.tsirikos@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  This is my resume/personal website in which you can find more
  information about me, my skills, my interests etc

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: compressed
######
#  docker run --rm -v="$PWD:/srv/jekyll" -p 4000:4000 -it jekyll/minimal:3.8 bash
